### ISSUE TITLE
Crash: Polygon tool cancellation dialog causes crash

### ISSUE THREAD

**Issue by mingrui** [maubreville/SlideRunner#12]
Bug in action: https://drive.google.com/open?id=1RTnrNJ8GvjM-gIwS8tUE5jg95V6eyIZJ

When using the polygon tool, without finishing the annotation, if I switch to another tool, a cancel confirmation dialog box will pop up. If I click yes, the program will crash.

Crash log:

```
Traceback (most recent call last):
  File "/mnt/960EVO/workspace/pathology/SlideRunner/SlideRunner/SlideRunner.py", line 663, in setUIMode
    self.showImage()
  File "/mnt/960EVO/workspace/pathology/SlideRunner/SlideRunner/SlideRunner.py", line 1347, in showImage
    npi = self.showPolygon(npi, self.ui.annotationsList, color=[0,0,0,255])
  File "/mnt/960EVO/workspace/pathology/SlideRunner/SlideRunner/SlideRunner.py", line 785, in showPolygon
    anno = self.slideToScreen(polygon[listIdx])
IndexError: list index out of range
[1]    21235 abort (core dumped)  python main.py
```

**Comment by maubreville** [comment]
Thanks for the detailed report. Was able to reproduce.
