### ISSUE TITLE
AttributeError: 'SlideRunnerUI' object has no attribute 'get_colors'

### ISSUE THREAD

**Issue by mingrui** [maubreville/SlideRunner#20]
Hi,

Recently working an a polygon ROI to .png patches plugin, updated to latest code, but it seems the polygon tool is breaking when "closing" a polygon.

at the end of my polygon drawing, I will double click and select a annotation label, then it crashes.
this is the error:

```
Traceback (most recent call last):
  File "/mnt/960EVO/workspace/pathology/SlideRunner-Master/SlideRunner/gui/annotation.py", line 50, in addPolygonAnnotation
    self.showAnnotationsInOverview()
  File "/mnt/960EVO/workspace/pathology/SlideRunner-Master/SlideRunner/SlideRunner.py", line 1003, in showAnnotationsInOverview
    self.tn_annot = self.overlayAnnotations(self.tn_annot, region=[np.zeros(2),tnsize], zoomLevel=self.thumbnail.downsamplingFactor, thickness=1, adjustList = False)
  File "/mnt/960EVO/workspace/pathology/SlideRunner-Master/SlideRunner/SlideRunner.py", line 1114, in overlayAnnotations
    image = self.showPolygon(tempimage=image, polygon=poly[0], color=self.get_colors(poly[1]))
AttributeError: 'SlideRunnerUI' object has no attribute 'get_colors'
[1]    12682 abort (core dumped)  python main.py
```

**Comment by maubreville** [comment]
Let me check this, I think we can resolve this quickly.
